project:
  type: website
  render:
    - "*.qmd"

website:
  title: "Traffic Estimation Using Open Data"
  search: false
  sidebar:
    style: "docked"
    contents:
      - index.qmd
      - section: "Estimation models"
        contents:
          - 0A_Causal_model.qmd
          - 0B_Data_sources.qmd
          - 0C_Estimator_selection.qmd
      - section: "Preprocessing"
        contents:
          - 1A_Count_data.qmd
          - 1B_Census_data.qmd
          - 1C_Road_network.qmd
format:
  html:
    toc: true