project:
  type: website
  render:
    - "*.qmd"

website:
  title: "Traffic Estimation Using Open Data"
  search: false
  sidebar:
    style: "docked"
    contents:
      - index.qmd
      - section: "Preprocessing"
        contents:
          - A1_Count_data.qmd
          - B1_Road_network.qmd
          - C1_Census_data.qmd
      - section: "Exploratory Analysis"
      - section: "Estimation models"
      
format:
  html:
    toc: true