project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
website:
  title: "Traffic Estimation Using Open Data"
  search: false
  sidebar:
    background: "secondary"
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/juanfonsecaLS1/GEOG5099_Analysis
          - text: Report an Issue
            url:  https://github.com/juanfonsecaLS1/GEOG5099_Analysis/issues/new/choose
    style: "docked"
    contents:
      - index.qmd
      - section: "Estimation models"
        contents:
          - 0A_Causal_model.qmd
          - 0B_Data_sources.qmd
          - 0C_Estimator_selection.qmd
      - text: "---"
      - section: "Preprocessing"
        contents:
          - 1A_Count_data.qmd
          - 1B_Census_data.qmd
          - 1C_Road_network.qmd
      - text: "---"
      - section: "Model Fitting"
format:
  html:
    toc: true