project:
  type: website
  render:
    - "*.qmd"

website:
  title: "Traffic Estimation Using Open Data"
  search: false
  sidebar:
    style: "docked"
    contents:
      - index.qmd
      - section: "Preprocessing"
        contents:
          - 1A_Count_data.qmd
          - 1B_Road_network.qmd
          - 1C_Census_data.qmd
      - section: "Exploratory Analysis"
      - section: "Estimation models"
        contents:
          - 2B_Causal_model.qmd
format:
  html:
    toc: true